Lesson17.IO/NIO.
OlegGorobets/nixalevel pull request #10
Opened 2022-08-05 22:05 UTC by OlegGorobets

2022-08-05 22:06 UTC, OlegGorobets commented
![](https://github.trello.services/images/mini-trello-icon.png) [IO/NIO](https://trello.com/c/eMeAgXiW/89-io-nio)

2022-08-06 22:29 UTC, Fabolo12 requested changes
Удали ветки которые уже смержены

2022-08-06 22:29 UTC, Fabolo12 commented on src/main/java/com/nixalevel/lesson10/Main.java
> +        vehicles.add(readFromFile.readFileAndCreateAuto("src/main/resources/readme.json"));
Чтение с файла не верное

2022-08-07 21:34 UTC, Fabolo12 approved these changes

2022-08-08 09:01 UTC, merged