Lesson23.JDBC.
OlegGorobets/nixalevel pull request #14
Opened 2022-08-28 15:54 UTC by OlegGorobets

2022-08-28 15:55 UTC, OlegGorobets commented
![](https://github.trello.services/images/mini-trello-icon.png) [JDBC](https://trello.com/c/Umfq0Qbk/149-jdbc)

2022-08-28 21:08 UTC, Fabolo12 requested changes
Работа с инвойсом не реализована

2022-08-28 21:09 UTC, Fabolo12 commented on src/main/java/com/nixalevel/lesson10/service/JDBCAutoService.java
> +public class JDBCAutoService extends VehicleService<Auto> {
Дополнительные сервисы не нужны

2022-09-01 22:24 UTC, OlegGorobets commented
![](https://github.trello.services/images/mini-trello-icon.png) [JDBC](https://trello.com/c/Umfq0Qbk/149-jdbc)

2022-09-02 23:18 UTC, Fabolo12 approved these changes

2022-09-03 16:04 UTC, merged