init. added lesson10.
OlegGorobets/nixalevel pull request #3
Opened 2022-07-07 20:29 UTC by OlegGorobets

2022-07-09 20:21 UTC, Fabolo12 requested changes

2022-07-09 20:21 UTC, Fabolo12 commented on src/main/java/com/nixalevel/lesson10/model/BusManufacturer.java
> +    Ikarus, Mercedes, MAN, Daewoo
Перечисления большими буквами

2022-07-09 20:21 UTC, Fabolo12 commented on src/main/java/com/nixalevel/lesson10/model/MotorbikeManufacturer.java
> +    Honda, Suzuki, Kawasaki, HarleyDavidson
И тут

2022-07-09 20:21 UTC, Fabolo12 commented on src/main/java/com/nixalevel/lesson10/model/Vehicle.java
> +    protected MotorbikeManufacturer motorbikeManufacturer;
Эти поля должны быть в конкретных классах, а не в абстракции

2022-07-09 20:21 UTC, Fabolo12 commented on src/main/java/com/nixalevel/lesson10/service/AutoService.java
> +        LOGGER.info("\nAuto " + autos.get(index) + " removed from the list.");
```suggestion
        final Auto auto = autos.get(index);
        AUTO_REPOSITORY.delete(auto.getId());
        LOGGER.info("\nAuto {} removed from the list.", auto);
```

2022-07-09 20:21 UTC, Fabolo12 commented on pom.xml
> +        </dependency>
Вот так будет работать логер
```suggestion
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.2.11</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.11</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.36</version>
        </dependency>
```

2022-07-15 22:48 UTC, Fabolo12 approved these changes

2022-07-15 22:48 UTC, Fabolo12 commented on src/main/java/com/nixalevel/lesson10/model/Vehicle.java
>      protected final String id;
А почему этот класс не абстрактный?

2022-07-16 12:33 UTC, OlegGorobets commented on src/main/java/com/nixalevel/lesson10/model/Vehicle.java
>      protected final String id;
> 

Сделал абстрактным😅

2022-07-16 12:37 UTC, merged