Lesson14.Collections 1.
OlegGorobets/nixalevel pull request #7
Opened 2022-07-24 13:12 UTC by OlegGorobets

2022-07-24 16:09 UTC, OlegGorobets commented
![](https://github.trello.services/images/mini-trello-icon.png) [Collections 1](https://trello.com/c/AyzL7mMq/51-collections-1)

2022-07-24 22:05 UTC, Fabolo12 requested changes

2022-07-24 22:05 UTC, Fabolo12 commented on src/main/java/com/nixalevel/lesson10/Main.java
> +        }
Сортировка должна была быть по трек критериям сразу, а не отдельно

2022-07-31 22:19 UTC, Fabolo12 approved these changes

2022-08-02 19:40 UTC, merged

2022-08-28 15:54 UTC, OlegGorobets commented
![](https://github.trello.services/images/mini-trello-icon.png) [JDBC](https://trello.com/c/Umfq0Qbk/149-jdbc)